### ISSUE TITLE
Can not install on macOS using pip3

### ISSUE THREAD

**Issue by zjzsliyang** [PyRadar/pyradar#9]
the error shows like:
```shell
Complete output from command python setup.py egg_info:
Traceback (most recent call last):
File "<string>", line 1, in <module>
    File "/private/var/folders/2m/0wb_fp1j5tq7_f7l72qwmkcw0000gn/T/pip-build-rcixqynu/pyradar/setup.py", line 85
    print "\n{}\n{}\n{}\n{}\n".format(msg, limits,
                                 ^
    SyntaxError: invalid syntax

Command "python setup.py egg_info" failed with error code 1 in /private/var/folders/2m/0wb_fp1j5tq7_f7l72qwmkcw0000gn/T/pip-build-rcixqynu/pyradar/
```

**Comment by gauravcusp** [comment]
I'm getting the same error. Any workaround?

**Comment by MarkusZehner** [comment]
managed to install it on macOS, #11 
hope that helps :) cheers!
